### ISSUE TITLE
Multiple projects

### ISSUE THREAD

**Issue by laughedelic** [inkytonik/atom-sbt#10] opened 2016-03-04 00:20 UTC
Would it be hard to support multiple running sbt instances and switch between them based on the open file?

**Comment by inkytonik** [comment] 2016-03-04 05:11
Hmm, seems possible but how would you want it to work? E.g., would it be enough to associate sbt sessions with open projects and send commands to the session associated with the project of the file that has the focus? Or did you have something else in mind?

**Comment by laughedelic** [comment] 2016-03-04 09:59
I had in mind exactly what you described. It would be enough for at least how I use atom and sbt :+1:

**Comment by laughedelic** [comment] 2016-03-04 15:05
One addition here: as you can add names to the terminal sessions, it would be better to put there project names, instead of just `sbt`.

**Comment by inkytonik** [comment] 2016-03-05 09:48
0.7.0 will include a change to add the project path (either full or just base name configured by a setting) to the terminal title. 

Having multiple sessions will take a bit longer...

**Comment by laughedelic** [comment] 2016-03-05 13:14
OK!

**Comment by laughedelic** [comment] 2016-03-05 20:51
About project name: if I have several sbt projects in the window and toggle sbt plugin for some of them, the name assigned to the terminal is the name of the first project in the window. For example, I have sbt-projects opened:
- `foo`
- `bar`
- `buh`

then I go to some file in `buh` and press `alt-shift-O` to toggle sbt. Sbt is running for the `buh` project as expected, but the terminal name is `sbt foo`.

**Comment by inkytonik** [comment] 2016-03-06 01:23
Yeah, at the moment the package doesn't handle multiple projects well. It just picks the first path. I'm working on a design to make this better but there a bunch of factors to take into account so I'll need a little time to think about it. In the meantime a workaround is to run the sets in different Atom windows.

**Comment by inkytonik** [comment] 2017-01-24 23:08
Finally found some time to work on this package. 6757e0abd986232d8e2e6744d2c0b426ed44f93d fixes the bug where the wrong project name would be used if it wasn't the first project in the window.

Full support for multiple projects is still in progress.

**Comment by inkytonik** [comment] 2017-01-27 04:06
A first cut at support for multiple projects in a single window has been committed in ade0873581907afd8bc46b9372082fe0edcf9ab4.

@laughedelic if you are able to try this it would be appreciated. It works for me, but a sanity check from a real user would be good before I do a release.

**Comment by laughedelic** [comment] 2017-03-03 02:28
Hi! Sorry, I totally missed last comments here 😓 
I just tried the version from `master` and I see that now a new console window appears when I call it from another project and it's correctly named 👍 But if I try to send a command to it (through the command panel), it just opens the window without any command inserted there.

**Comment by inkytonik** [comment] 2017-03-05 22:59
No worries. Thanks for checking it out. Unfortunately, I can't reproduce the problem you are seeing. I open two projects in one Atom window, create sbt terminal windows for each and I can send commands successfully to the two windows (both via key mappings and via the command palette).

I'm clearly not doing exactly what you are doing. Can you give me a step-by-step way to reproduce it?

**Comment by laughedelic** [comment] 2017-03-06 21:18
What is the right way to install unreleased versions of plugins? I just clone the repo to `~/.atom/packages/sbt/` and run `apm install` there. I tried both ade0873 and the latest in `master`.

When I run any command with sbt (compile, toggle panel, whatever) it opens a new terminal panel for the right project with the right name and loads the project. But any attempts to send a command don't have any effect. 

I still can enter the command manually, like `~compile`, but once I change a source to check that it actually works, it breaks the plugin:

**Atom**: 1.15.0-beta4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [sbt](https://github.com/inkytonik/atom-sbt) package 0.8.0

### Stack Trace

Uncaught ReferenceError: project is not defined

```
At /Users/laughedelic/.atom/packages/sbt/lib/project.coffee:145

ReferenceError: project is not defined
    at Project.module.exports.Project.processData (/packages/sbt/lib/project.coffee:145:22)
    at /packages/sbt/lib/project.coffee:68:10
    at /app.asar/src/task.js:126:25
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/task.js:78:34)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
  3x -3:23.1.0 sbt:compile (input.hidden-input)
  2x -3:21.5.0 pane:show-previous-item (input.hidden-input)
     -3:13.3.0 command-palette:toggle (input.hidden-input)
     -3:11.1.0 core:confirm (input.hidden-input)
     -3:11.1.0 sbt:exit (input.hidden-input)
     -3:07.0 sbt:toggle-panel (textarea.)
     -3:04.8.0 sbt:compile (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:03.6.0 linter:expand-multiline-messages (input.hidden-input)
  4x -3:02.9.0 sbt:compile (input.hidden-input)
     -2:14.3.0 sbt:toggle-panel (textarea.)
     -2:12.1.0 sbt:compile (input.hidden-input)
     -2:10.5.0 linter:expand-multiline-messages (input.hidden-input)
  2x -0:58.6.0 sbt:toggle-panel (input.hidden-input)
     -0:21.7.0 vim-mode-plus:delete-right (input.hidden-input)
     -0:21.3.0 core:save (input.hidden-input)
  2x -0:09.8.0 sbt:toggle-panel (input.hidden-input)
```

**Comment by inkytonik** [comment] 2017-03-06 23:29
My usual practice for testing this kind of thing is to clone the package into the dev package directory and run Atom in dev mode (or Open Dev from the command palette). See this post for some instructions: https://discuss.atom.io/t/load-developing-package/2554/2.

**Comment by laughedelic** [comment] 2017-03-07 15:04
Thanks. I tried it and I get the same bahavior and the same error. It refers to `lib/project.coffee:145`, which looks a bit strange to me:

```coffescript
  processData: (data) ->
    if @pendingClear
      @clearMessages(project) // <-- here
      @pendingClear = false
    // ...
```

Method `cleasMessages` doesn't seem to take parameters. And this reference to `project` is unclear.. Anyway, I'm just guessing, I think you know what's actually going on.

**Comment by inkytonik** [comment] 2017-03-08 22:44
Yes, you're right. I don't use continuous commands (~) very much so I always forget to test that functionality. I've pushed bbf17f5b8ccb18d994f4cc55fbbcdd06ce3c8ba5 which fixes that problem.

**Comment by laughedelic** [comment] 2017-03-08 23:21
Well, it doesn't break now, but the behaviour is not very consistent. 
- If I have 4 errors in one project and none in another, the linter shows 4 errors and jumps to them even from the files of the seconds project. 
- Now if I add an error in the second project, it shows just 1 error and forgets about the others. And if I fix it, it shows no errors and doesn't remember about the first project.

I think that errors among sbt-project in the same window should get accumulated. Also I was wondering whether it would be possible to move the `clearMessages` action to the end of the compilation, so that it doesn't switch to "No issues" while compiling (with possible errors after that).

**Comment by inkytonik** [comment] 2017-03-08 23:40
Ah, this is very useful feedback, because I confess that I wasn't sure the best way to make this work, so the current design is not set in stone.

Currently, as you noted, I will only show errors from one project at a time (the most recently built one). My reasoning is that if you are working on two projects together, it is likely that rebuilding one of them might change the error status of the other one and you will have to rebuild it anyway. So, it seemed wrong to leave "in play" the errors from the project that you are not building. Thus, at the moment any build causes the sbt errors to be cleared. Does this logic make sense to you? 

I guess I"m not imagining a scenario where you would run a bunch of builds in different projects and then go through fixing the errors. I was thinking it would make more sense to do a one-by-one approach.

It's not clear that I can easily (or should) stop the "jump to errors in another project" behaviour since that's the way the linter works already. There's just one global collection of current messages. I would probably need to override the linter commands to make them project-specific but that would be counter-intuitive to existing linter users, I think.

**Comment by inkytonik** [comment] 2017-03-09 05:49
Thinking further on this, I think I should be able to have a separate linter client for each sbt project that has a running session. Then it would be possible to just clear the messages for the current project. But I think it's probably worth making this optional, because I think I would find that behaviour confusing.

**Comment by laughedelic** [comment] 2017-03-12 18:58
> it seemed wrong to leave "in play" the errors from the project that you are not building

I see your point. 

> I guess I"m not imagining a scenario where you would run a bunch of builds in different projects and then go through fixing the errors. I was thinking it would make more sense to do a one-by-one approach.

Right, I think the problem is not jumping between different project errors, but rather updating the linter state when you switch between project files. I don't know if it's possible. Probably having a linter per project will help. I'm not familiar with linter API..

**Comment by laughedelic** [comment] 2017-03-15 22:51
About better status indication: [linter v2](http://steelbrain.me/2017/03/13/linter-v2-released.html) has something called Busy Signal Integration. This would be super nice to turn on while sbt is compiling so that it's obvious when the summary indicator (with number of errors/warnings) is yet to be updated.

**Comment by inkytonik** [comment] 2017-03-15 23:09
Yes, I agree that a status indicator will be useful. I had hacked one together myself but something supported by the linter will be better. I'll look into linter v2 properly as soon as I can.

**Comment by inkytonik** [comment] 2017-04-03 01:26
As of 475958c74efcc25f09696f7c456deb9d1b18d615 there are per-project linters. I think it's working nicely but if you have a chance to try the latest master version that would be great.

**Comment by inkytonik** [comment] 2017-04-03 01:28
Also, linter V2 is now supported as of a22c61b182995b72200dd860a7c4788a8bdac89f. Please report problems on #16.

**Comment by laughedelic** [comment] 2017-04-03 10:44
Great! I will try out the latest master version.

**Comment by laughedelic** [comment] 2017-04-03 11:19
What I see now in the linter status is the total number of errors from all projects in the window. Is it how it's supposed to be? I though that per-project linters will maintain their own state and switch status panel when switching between files.

**Comment by inkytonik** [comment] 2017-04-03 20:56
Hmm, not sure. As far as I can see there is nothing that I can do except use a separate linter for each sbt project which I am now doing.

It seems that the "Statusbar presents" setting in the Linter UI only has "Current File" and "Entire Project" where the latter is interpreted to mean anything that's open in the window. Arguably there should be an "Entire Window" setting and "Entire Project" should be just for the project of the current file. Perhaps this is an issue for them?

**Comment by laughedelic** [comment] 2017-04-04 10:43
OK, I see. I'm fine with window-total. Just wanted to make sure it works as supposed.

**Comment by inkytonik** [comment] 2017-04-19 02:34
Supported in version 0.9.0 which is now published.

**Closed as completed by inkytonik** 2017-04-19 02:34 UTC
Labels: enhancement
